language: ruby
rvm:
- 2.2.1
branches:
  only:
  - master
install:
- travis_retry bundle install
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rspec
before_script:
- psql -c 'create database "soup-du-jour_test";' -U postgres